version: '3'
services:

#  mysql:
#    container_name: site-mysql
#    image: mysql/mysql-server:5.7
#
#    environment:
#      MYSQL_DATABASE: register
#      MYSQL_ROOT_PASSWORD: zemsite2019
#      MYSQL_ROOT_HOST: '%'
#    expose:
#      - "3306"
#    volumes:
#      - /data/mysql
#    restart: always

  app:
    network_mode: host
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
#    depends_on:
#        - mysql
    volumes:
      - /home/gis/storage:/data/spring-boot-app
    ports:
      - "8083:8083"
volumes:
  - /home/gis/storage:



